### ISSUE TITLE
Unable to install openCV

### ISSUE THREAD

**Issue by Vijayjangra21** [lanzani/jetson-docs#6]
After running every command on the link: https://jetson-docs.com/libraries/opencv/l4t32.7.1/py3.8.0

I'm not able to install openCV 4.8.0

After running the command `python3 -c "import cv2; print('OpenCV version:', str(cv2.__version__)); print(cv2.getBuildInformation())"` I get the following error:

```
python3
Python 3.8.0 (default, Dec  9 2021, 17:53:27)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.6/site-packages/cv2/__init__.py", line 112, in bootstrap
    load_first_config([
  File "/usr/local/lib/python3.6/site-packages/cv2/__init__.py", line 109, in load_first_config
    raise ImportError('OpenCV loader: missing configuration file: {}. Check OpenCV installation.'.format(fnames))
ImportError: OpenCV loader: missing configuration file: ['[config-3.8.py](http://config-3.8.py/)', 'config-3.py']. Check OpenCV installation
```

Pls note: I've added the line: `export PYTHONPATH=/usr/local/lib/python3.6/site-packages:$PYTHONPATH` in the bashrc file.

**Comment by lanzani** [comment]
Hello! 
You are using the jetson nano right?

I will look into that, in the meanwhile, have you considered using the [docker image](https://jetson-docs.com/libraries/opencv/overview#runtime-images) with python3.8.0 and opencv 4.8.0?

**Comment by lanzani** [comment]
Any news on this issue?
